config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "/", path_names: { sign_in: "login", sign_out: 'logout', sign_up: "signup" }, :controllers => { registrations: 'registrations' }
 
  root to: "users#home"
  get "/users/preview", to: "users#preview", as: "preview"
  resources :users
  get "/pages/donate", to: "pages#donate"
  get "/pages/underconstruction", to: "pages#underconstruction"
  post "/payments", to: "payments#stripe"
  get "/payments/success", to: "payments#success"

  get "/inbox", to: "conversations#index", as: "conversations"
  post "/inbox", to: "conversations#create"
  get "/inbox/:conversation_id/messages", to: "messages#index", as: "conversation_messages"
  post "/inbox/:conversation_id/messages", to: "messages#create"

  get "/saved", to: "follows#index", as: "saved"
  resources :follows, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  before_save :sanitize_strings
  # Devise modules
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Defining Role enum
  enum role: { Developer: 0, Designer: 1 }

  # Associations
  has_one :location
  has_many :users_skills, dependent: :destroy
  has_many :skills, through: :users_skills
  has_many :messages, dependent: :destroy
  has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow'
  has_many :followees, through: :followed_users
  has_many :following_users, foreign_key: :followee_id, class_name: 'Follow'
  has_many :followers, through: :following_users
  has_one_attached :picture

  # validates :first_name, :last_name, :role, :location_id, presence: true, :on => :update, :if => :run_form_validation

  private
    # Clean up strings before they are saved to database
    def sanitize_strings
      self.first_name = self.first_name.strip.titleize unless self.first_name.blank?
      self.last_name = self.last_name.strip.titleize unless self.last_name.blank?
      self.occupation = self.occupation.strip.titleize unless self.occupation.blank?
    end
    
  # Validation attempted here but required 2-step process (Devise creation for email and password, and then profile update after donation)
  # Validation with if/unless prevented intermediary stripe_payment from being saved 
  # and user kept being redirected to donation page
  # Put validation in controller and check for @user attributes i.e.:
  # if @user.first_name && @user.last_name && @user.role && @user.location_id

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:index, :edit, :show, :new]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :search, only: [:index, :home, :preview]
  before_action :authorize_user, only: [:edit, :update, :destroy]
  before_action :set_roles_locations_skills, only: [:new, :edit]
  before_action :redirect_to_donate, only: [:index, :show, :edit, :new]
  before_action :redirect_to_update_profile, only: [:index, :show, :edit]
  before_action :update_skills, only: [:update]

  def index
  end

  def home
  end 

  def preview
  end 

  def show
    # Fallback so that users can't access other users profiles if their own profile isn't complete
    if @user.profile_complete != true
      redirect_to users_path
    else
      location_id = @user.location_id 
      @location = Location.find(location_id)
    end
  end

  def new
    @user = current_user
  end

  def edit
  end

  def create
    # Omitted because Devise creates user, and User only ever updates user after Devise creation.
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: 'Profile saved!' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end

    if @user.first_name && @user.last_name && @user.role && @user.location_id
      @user.profile_complete = true
      @user.save
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def search 
      # Eager loading the pool of users ordered alphabetically by last name, only showing those with completed profiles
      @users = User.all.order(:last_name).where(profile_complete: true).includes(:skills)

      # Filter search by first name and/or last name
      unless params[:string].blank?
      @users = @users.where("lower(first_name || ' ' || last_name) LIKE ?", "%#{params[:string].downcase}%")
      end 
      
      # Filter search by location
      @locations = Location.all.pluck(:name)
      unless params[:location].blank?
        @location_name = params[:location]
        location_id = Location.find_by(name: @location_name)
        @users = @users.where(location_id: location_id)
      end
      
      # Filter search by designer/developer
      @roles = User.roles.keys
      unless params[:role].blank?
        @role_name = params[:role]
        role_enum = User.roles[@role_name]
        @users = @users.where(role: role_enum)
      end
      
      # Filter search by single skill (for home/landing page)
      skilled_users = []
      unless params[:skill].blank?
        @skill_name = params[:skill]
        skill_id = Skill.find_by(name: @skill_name).id
        @users.each do |user|
          skilled_users << user if user.skills.ids.include?(skill_id)
        end 
        # @users = skilled_users
        @users = User.where(id: skilled_users.map(&:id))
      end 
      
    
      # Filter search by skills for index page (primary search)
      @skills = Skill.all
      unless params[:skills].blank?
        # Converting all skill ids passed through params to integers, yielding an array e.g. [1, 2, 3]
        skill_ids = params[:skills].map { |skill_id| skill_id.to_i }
        # initialising empty array of users who have matching skills
        @users.each do |user| 
          # adding the user to the skilled users array if the user knows all of the skills passed through the checkbox form
          skilled_users << user if skill_ids.all? { |skill| user.skills.ids.include?(skill) }
        end
        @users = User.where(id: skilled_users.map(&:id))

      end

    # returning the filtered list of users after performing all relevant search methods
    @users = @users.page(params[:page])
    end 

    # Defining instance variables
    def set_roles_locations_skills
      @roles = User.roles.keys
      @locations = Location.all
      @skills = Skill.all
      # Defines skills that the current user knows for pre-checking checkboxes
      @selected_skills = current_user.skills.pluck(:name)
    end

    # Method to add skills to current user's skills when checkboxes marked
    def update_skills
      current_user.skills = []
      @skill_ids = params[:skills]
      @skill_ids.each { |skill_id| current_user.skills << Skill.find(skill_id) } unless @skill_ids.blank?
    end

    def set_user
      id = params[:id]
      @user = User.find(id)
    end

    # Prevent user from performing unauthorized actions i.e. editing someone else's profile
    def authorize_user
      if @user.id != current_user.id || current_user.id == 1
        redirect_to users_path, notice: 'You are not authorised to perform this action.'
      end
    end

    # Whitelisting parameters for forms
    def user_params
      params.require(:user).permit(:picture, :first_name, :last_name, :age, :role, :skills, :bio, :portfolio_url, :occupation, :location_id)
    end

    # Redirecting users back to donate page, preventing them from entering unless payment successful
    def redirect_to_donate
       if current_user.stripe_payment != true
        redirect_to "/pages/donate", notice: 'Please donate before continuing.'
       end
    end

    # Preventing users from searching/viewing other users unless their profile is complete
    def redirect_to_update_profile
      if current_user.profile_complete != true
        redirect_to new_user_path, notice: 'You need to fill in your profile before you proceed!'
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
  <% if user.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="text-left m-auto">
  <%= form_with model: user, local: true do |form| %>
    <div class="form-group row">
      <div class="col-md-6">
        <%= form.label :picture, "Upload a profile picture", class: "label" %>
      </div>
      <div class="col-md-6">
        <%= form.file_field :picture, accept: 'image/png,image/gif,image/jpeg,image/jpg', class: "filestyle" %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6 mb-2">
        <%= form.label :first_name, class: "label" %>
        <%= form.text_field :first_name, class: "form-control", :required => true %>
      </div>
      <div class="col-md-6 mb-2">
        <%= form.label :last_name, class: "label" %>
        <%= form.text_field :last_name, class: "form-control", :required => true %>
      </div>
    </div>

    <fieldset class="form-group">
      <div class="row">
        <legend class="col-form-label pt-0 sr-only label">I'm a</legend>
        <% roles.each do |option| %>
          <div class="form-check col-md-6">
              <%= form.radio_button :role, option, class: "mr-2 mt-4" %>
              <%= form.label "role_#{option}".to_sym, "I'm a #{option}", :required => true, class: "form-check-label" %>
          </div>
        <% end %>
      </div>
    </fieldset>
    <div class="form-group row">
      <div class="col-md-6 label mt-3">
        Skills you know
      </div>
    </div>

    <div class="form-group row">
      <div class="col-md-4">
      <% @skills.each_with_index do |skill, i| %>
          <% if @selected_skills.include?(skill.name) %>
            <input class="checkbox mr-2" type="checkbox" name="skills[]" id="<%= skill.id %>" value="<%= skill.id %>" checked> <label for="<%= skill.id %>"><%= skill.name %></label><br>
          <% else %>
            <input class="checkbox mr-2" type="checkbox" name="skills[]" id="<%= skill.id %>" value="<%= skill.id %>"> <label for="<%= skill.id %>"><%= skill.name %></label><br>
          <% end %>
        <% if i == 5 or i == 11 %>
          </div>
          <div class="col-md-4">
        <% end %>
      <% end %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-4">
        <%= form.label :age, class: "label" %>
        <%= form.number_field :age, class: "form-control mb-2", min: 18 %>
      </div>
      <div class="col-md-8 form-group">
        <%= form.label :location_id, class: "label" %>
        <%= form.select(:location_id, locations.map{ |location| [location.name, location.id] }, {include_blank: 'Pick a Location'}, {required: true, class: "form-control form-control-md"}) %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <%= form.label :occupation, class: "label" %>
        <%= form.text_field :occupation, class: "form-control mb-2"  %>
      </div>
      <div class="col-md-6">
        <%= form.label :portfolio_url, class: "label" %>
        <%= form.url_field :portfolio_url, class: "form-control mb-2" %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <%= form.label :bio, class: "label" %>
        <%= form.text_area :bio, class: "form-control mb-2", rows: 5, resize: false %>
      </div>
    </div>

    <div class="mb-3 form-group text-center">
      <%= form.submit "Save", class: "mt-3 w-100 btn btn-primary btn-blocks" %>
    </div>


  <% end %>
  </div>

app/views/users/_search_results.html.erb
<% if @users.blank? %>
  <div class="w-100 p-4">
    <h4>Sorry, we couldn't find anyone that matches your search. Try again!</h4>
  </div>
<% else %>
  <div class="w-100">
    <% @users.each do |user| %>
      <div class="card mb-3">
        <div class="card-body p-3">

          <div class="row">

            <div class="col-9 p-0 pl-3">
              <div class="row m-auto">
                <div class="circle search ml-2">
                  <%= link_to user_path(user.id) do %>
                    <%= image_tag user.picture if user.picture.attached? %>
                  <% end %>
                </div>
                <div class="pl-3 my-auto">
                  <div class="row m-auto">  
                    <%= link_to user_path(user.id) do %><%= user.first_name %> <%= user.last_name %><% end %>
                  </div>
                  <div class="row m-auto">
                    <%= user.role %>
                  </div>
                </div>
              </div>
              <div class="row p-0 m-auto">
                <% user.skills.each do |skill| %>
                  <div class="card w-auto p-1 pl-2 pr-2 m-1 text-muted small btn-default-sm">
                    <%= skill.name %>
                  </div>
                <% end %>
              </div>
            </div>

            <div class="col-3 d-flex flex-column justify-content-between pl-0">
              <div class="row m-0 ml-auto">
                <% if current_user.followers.where(id: user.id).exists? %>
                  <%= link_to icon("fas", "star"), follow_path(id: user.id), method: :delete %>
                <%else%>
                  <%= link_to icon("far", "star"), follows_path(id: user.id), method: :post %>
                <%end%>
              </div>
              <div class="row m-0 text-right ml-auto">
                <%= button_to "Message", conversations_path(sender_id: current_user.id, receiver_id: user.id), method: :post, class: "btn btn-primary small" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%= paginate @users %>
<% end %>

app/views/users/edit.html.erb
<div class="form-lg p-4 mt-5 mb-5 text-center">
  <h1 class="mb-5 pb-3">Edit your Profile</h1>

<%= render 'form', user: @user, roles: @roles, locations: @locations, skills: @skills %>
</div>

app/views/users/home.html.erb
<div class="home">
<div class="container">
    <div class="row mt-md-5">
        <div class="col-md-8 p-3">
            <h1>Discover designers and devs.<br />
            Learn and share skills.</h1>
            <p class="pt-3">Cocobuds is a platform that helps you connect with designers and developers in your area. It's a great way to learn and share skills while expanding your network.</p>
            <%= button_to("Get started", "#search", {method: :get, class: "btn btn-primary mt-3"})%>
        </div>
        <div class="col-md-4">
        </div>
    </div>

        <div class="row">
            <div class="col-md-6 p-3 text-right">
            </div>
            <div class="col-md-6 p-3">
                <%= image_tag "cocobuds_landing_page_friends.jpg", class:"img-fluid" %>
            </div>
        </div>

        <div class="row mt-md-5">
            <div class="col-md-3 p-3 text-right">
                <h2>It's not</h2>
            </div>
            <div class="col-md-7 p-3 mt-4 text-right">
                <h2>just what it looks like<br /> and feels like.</h2>
                <h2 class="mt-md-4">Design is how it works.</h2>
                <p>Steve Jobs</p>
            </div>
            <div class="col-md-2 p-3">
            </div>
        </div>


  <div class="row landing justify-content-between pt-5" id="search">
    <div class="col-md-5 p-3 pt-5 mt-md-5">
      <h2 class="mb-4">Find a Cocobud</h2>
      <%= form_with url: preview_path, method: :get, local: true do |form| %>
        <div class="form-group">
            <%= form.label :location, "Pick a location", class: "sr-only" %>
            <%= form.select(:location, options_for_select( @locations, params[:location] ), {include_blank: 'Pick a Location'}, {required: true, class: "form-control form-control-md"}) %>
        </div>
        <div class="form-group">
            <%= form.label :role, "Looking for a developer or a designer?", class: "sr-only" %>
            <%= form.select(:role, options_for_select( @roles, params[:role] ), {include_blank: 'Find a developer or a designer?'}, {required: true, class: "form-control form-control-md"}) %>
        </div>
        <div class="form-group">
            <%= form.label :skill, "What skills do you have?", class: "sr-only" %>
            <%= form.select(:skill, options_for_select( @skills.pluck(:name), params[:skill] ), {include_blank: 'Select a Skill'}, {required: true, class: "form-control form-control-md"}) %>
        </div>
        <div class="mb-3 form-group text-center">
        <%= form.submit 'Search', class: "mt-3 w-100 btn btn-primary btn-blocks" %>
        </div>
      <% end %>
    </div>
    <div class="col-md-6 p-3 pt-5 mt-md-5 mr-n2">
        <%= image_tag "search_friends.svg", class:"img-fluid" %>
    </div>
</div>
</div>

app/views/users/index.html.erb
<div class="w-100 mt-4 p-5">
  <div class="row">
    <div class="mb-5 col-md-4">
      <%= form_with url: users_path, method: :get, local: true do |form| %>
        <div class="form-group">
          <%= text_field_tag :string, params[:string], class: "form-control form-control-sm", placeholder: "Search by Name" %>
        </div>
        <div class="form-group">
            <%= form.label :location, class: "sr-only" %>
            <%= form.select(:location, options_for_select( @locations, params[:location] ), {include_blank: 'Location'}, {class: "form-control form-control-sm"}) %>
        </div>
        <div class="form-group">
            <%= form.label :role, "Developer or Designer?", class: "sr-only" %>
            <%= form.select(:role, options_for_select( @roles, params[:role] ), {include_blank: 'Developer or Designer?'}, {class: "form-control form-control-sm"}) %>
        </div>
         <button class="btn btn-outline-primary btn-block btn-sm" type="button" data-toggle="collapse" data-target="#skills" aria-expanded="false" aria-controls="skills">
          Filter by skills
        </button>
        <div class="mt-3 form-actions collapse" id="skills">
          <div class="row">
          <div class="col">
          <% @skills.each_with_index do |skill, i| %>
            <% if i == (@skills.length / 2) - 1 %>
          </div>
          <div class="col p-0">
            <% end %>
            <input class="checkbox mr-1" type="checkbox" name="skills[]" id="<%= skill.id %>" value="<%= skill.id %>"> <label for="<%= skill.id %>" class="small"><%= skill.name %></label><br>
          <% end %>
          </div>
          </div>
        </div>
        <div class="mb-3 form-group text-center">
        <%= form.submit 'Search', class: "mt-3 w-100 btn btn-primary btn-blocks" %>
        </div>
      <% end %>
    </div>
    <div class="mb-5 col-md-8">
      <%= render 'search_results' %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="form-lg p-4 mt-md-5 mb-md-5 text-center">
  <h1 class="mb-5 pb-3">Create a Profile</h1>

<%= render 'form', user: @user, roles: @roles, locations: @locations, skills: @skills %>
</div>

app/views/users/preview.html.erb
<div class="custom-container landing p-5">
    <div class="m-auto">
        <h5 class="mb-5 mt-md-5 display-4 text-center">
            <% if @users.length == 0 %>
                Sorry, there are no <%= @role_name %>s in <%= @location_name %> who know <%= @skill_name %>.
            <% elsif @users.length == 1%>
                There is 1 <%= @role_name %> in <%= @location_name %> who knows <%= @skill_name %>.
            <% elsif @users.length > 1%>
                There are <%= @users.length %> <%= @role_name %>s in <%= @location_name%> who know <%= @skill_name %>.
            <% end %>
        </h5>
    </div>
    <div class="text-center">
        <% if @users.length == 0 %>
            <%= button_to("Try again?", "/#search", {method: :get, class: "mb-3 btn btn-primary btn-default btn-lg"})%>
            <div class="text-center mb-5">
                <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "Login", new_user_session_path %>
            </div>
        <% else %>
            <%= button_to("Sign up to meet them!", new_user_registration_path, {method: :get, class: "mb-3 btn btn-primary"})%>
            <div class="text-center mb-5">
                Already signed up? <%= link_to "Login", new_user_session_path %>
            </div>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<div class="custom-container m-auto p-3 pt-5">
  <div class="row">
    <div class="mb-2 col-md-4 profile">
      <div class="circle">
        <% if @user.picture.attached? %>
          <%= image_tag @user.picture %>
        <% else %>
           <%= image_tag "default.png" %>
        <% end %>
      </div>
      <p>
        <span class="font-weight-bold"><%= @user.first_name %> <%= @user.last_name %></span> <%= "/ #{@user.age}" unless @user.age.blank? %><br>
        <%= @user.role %><br>
        <%= @user.occupation %><br>
        <%= @location.name %>
      </p>
      <div class="row">
        <div class="col-1">
          <% if current_user.followers.where(id: @user.id).exists? %>
            <%= link_to icon("fas", "star"), follow_path(id: @user.id), method: :delete %>
          <%else%>
            <%= link_to icon("far", "star"), follows_path(id: @user.id), method: :post %>
          <%end%>
        </div>
        <div class="col-1">
          <%= link_to icon("far", "comment"), conversations_path(sender_id: current_user.id, receiver_id: @user.id), method: :post %>
        </div>
        <div class="col-1">
          <%= link_to icon("fas", "globe"), @user.portfolio_url, target: "_blank" %>
        </div>
      </div>
      <div class="m-auto">
        <% if @user.id == current_user.id && current_user.id != 1 %>
          <%= button_to("Edit", edit_user_path(@user), {method: :get, class: "mt-3 btn btn-outline-primary small"})%>
        <% end %>
      </div>

    </div>
    <div class="profile mb-5 mt-md-5 col-md-8 pt-2">
        <strong>About Me</strong>
        <p>
          <%= @user.bio %>
        </p>
      
      <div class="card-columns row p-2">
        <% @user.skills.each do |skill| %>
          <div class="card w-auto p-2 pl-3 pr-3 m-1 small btn-default-sm">
            <%= skill.name %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>